name: Docker Image Publishing

on:
  push:
    branches: [main]  # Trigger on pushes to the main branch

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@83a00bc1ab5ded6580f31df1c49e6aaa932d840d
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@b3eddbb94c4146a0988a620b01720afe50639271
        with:
          context: .  # Build context (path to Dockerfile)
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.run_number }}
            ghcr.io/${{ github.repository }}:latest
